version: '3'

services:
  generator:
    image: praba-registry:55000/praba-api:ci-${PRABAAPI_BUILD_NUMBER-14}
    ports:
      - "8080:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "8081:8025"