version: '3'

services:
  generator:
    image: praba-registry:55000/praba-api:ci-${PRABAAPI_BUILD_NUMBER-14}
    ports:
       - "${PORT_GENERATOR-8080}:80"
  mail:
    image: mailhog/mailhog
    ports:
      - "${PORT_MAILHOG-8081}:8025"